"""initial

Revision ID: 125642c284ae
Revises: 
Create Date: 2023-02-05 23:44:31.015586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125642c284ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
