"""init logs

Revision ID: 14a25f013f5b
Revises: 5c2ca8638b66
Create Date: 2023-03-12 23:03:13.626099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14a25f013f5b"
down_revision = "5c2ca8638b66"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bot_name", sa.String(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("logs")
    # ### end Alembic commands ###
