"""change column name to created_at in logs

Revision ID: 5a8664d54847
Revises: 8317c251812e
Create Date: 2023-03-12 23:11:41.710026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5a8664d54847"
down_revision = "8317c251812e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("logs", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.drop_column("logs", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "logs",
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.drop_column("logs", "created_at")
    # ### end Alembic commands ###
