"""init version

Revision ID: 5c2ca8638b66
Revises: 
Create Date: 2023-03-01 22:40:02.059844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c2ca8638b66"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("data", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("word", sa.String(length=500), nullable=False),
        sa.Column("transcription", sa.String(), nullable=True),
        sa.Column("translation", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("word"),
    )
    op.create_table(
        "guesses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("word_id", sa.Integer(), nullable=True),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("last_query_at", sa.DateTime(), nullable=True),
        sa.Column("last_reply_at", sa.DateTime(), nullable=True),
        sa.Column("is_success_last_time", sa.Boolean(), nullable=True),
        sa.Column("user_translation", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["clients.chat_id"],
        ),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guesses")
    op.drop_table("words")
    op.drop_table("events")
    op.drop_table("clients")
    # ### end Alembic commands ###
