"""add source column in logs

Revision ID: 8317c251812e
Revises: 14a25f013f5b
Create Date: 2023-03-12 23:08:04.563578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8317c251812e"
down_revision = "14a25f013f5b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("logs", sa.Column("source", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("logs", "source")
    # ### end Alembic commands ###
