"""alpha version

Revision ID: c542c3d73310
Revises: 125642c284ae
Create Date: 2023-02-05 23:54:48.897377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c542c3d73310'
down_revision = '125642c284ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('transcription', sa.String(), nullable=True),
    sa.Column('default_translation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_try_at', sa.DateTime(), nullable=True),
    sa.Column('user_translation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guesses')
    op.drop_table('words')
    op.drop_table('clients')
    # ### end Alembic commands ###
