"""add chat_id

Revision ID: eb26f2c4b869
Revises: c542c3d73310
Create Date: 2023-02-11 13:18:17.389830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb26f2c4b869'
down_revision = 'c542c3d73310'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guesses', sa.Column('chat_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'guesses', 'clients', ['chat_id'], ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guesses', type_='foreignkey')
    op.drop_column('guesses', 'chat_id')
    # ### end Alembic commands ###
